name: build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile
        run: |
          g++ main.cpp interception.c -O2 -static -o edfix.exe

      - uses: actions/upload-artifact@v4
        with:
          name: edfix
          path: edfix.exe
